package receiver.exception;

import static org.junit.Assert.*;
import org.junit.Test;

public class TestUndoException {
	
	@Test(expected=UndoException.class)
	public void TestUndo(){
		
		
	}
	
}

